### PR TITLE
answers for lesson 7

### PR DESCRIPTION
**Pull request by jaheemprevost**

### CODE REVIEW

**Review by KheffyC — APPROVED** [review]
nice job, Jaheem! Everything looks good, keep it up. Let me know if you have any questions going forward.

**Comment by jaheemprevost** [comment]
Thank you! I was actually wondering about the way the query parameters were being handled using conditional statements along with the way the pagination was implemented. Would that be the standard way of doing it or is there a more streamlined/efficient method? Also are there any articles/resources that I could read up on about it?

**Comment by KheffyC** [comment]
The way its written is just a way for you to double check that the query object that is being sent in the request is **correctly sent back to Mongoose**. 
_If_ its not correct, then you're modifying the data so that you don't send back an error to Product.find. This also allows you to pass data that isnt in your model Schema that you can use later in the controller function.  

- Another way to do this would be to set a default queryObj that 
 === {featured: false, company: 'insert default company', name: 'insert default name', fields: 'default fields'} etc. 
So that when you hit the route, it returns data regardless of the query having a payload or not. Does that make sense?

**Pagination**
- There are modules that you can install that have pagination set up once you import them if you would like to go that route. But I think the way it is written in the code works well and you can adjust and modify it to your liking since it isnt an import.

**Comment by jaheemprevost** [comment]
Yes it does, Thank you!

**Pull request merged**
